# Generated by Django 6.0 on 2026-01-04 16:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user_status', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อที่ใช้แสดง')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='plotcraft_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='plotcraft_user_set_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'ชาย'), ('F', 'หญิง'), ('O', 'อื่นๆ')], max_length=1)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('appearance', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_characters', to=settings.AUTH_USER_MODEL)),
                ('relationships', models.ManyToManyField(blank=True, related_name='related_to', to='plotcraft.character')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('world_type', models.CharField(blank=True, help_text='Ex: Fantasy, Sci-Fi, Omegaverse', max_length=100)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='location_maps/')),
                ('terrain', models.TextField(blank=True, help_text='ลักษณะภูมิประเทศ')),
                ('climate', models.TextField(blank=True, help_text='สภาพอากาศ')),
                ('ecosystem', models.TextField(blank=True, help_text='ระบบนิเวศ')),
                ('history', models.TextField(blank=True, help_text='ประวัติศาสตร์ความเป็นมา')),
                ('myths', models.TextField(blank=True, help_text='ตำนานและเรื่องเล่า')),
                ('politics', models.TextField(blank=True, help_text='การปกครอง')),
                ('economy', models.TextField(blank=True, help_text='ระบบเศรษฐกิจ')),
                ('culture', models.TextField(blank=True, help_text='วัฒนธรรม ความเชื่อ ศาสนา')),
                ('language', models.TextField(blank=True, help_text='ภาษาที่ใช้')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residents', models.ManyToManyField(blank=True, related_name='resides_in', to='plotcraft.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plotcraft.location'),
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อเรื่อง')),
                ('synopsis', models.TextField(blank=True, verbose_name='คำโปรย/เรื่องย่อ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='novel_covers/', verbose_name='รูปปก')),
                ('category', models.CharField(choices=[('FANTASY', 'แฟนตาซี (Fantasy)'), ('BL', 'วาย (Boy Love)'), ('GL', 'ยูริ (Girl Love)'), ('ROMANCE', 'รักโรแมนติก'), ('SCIFI', 'ไซไฟ/อนาคต'), ('ACTION', 'แอคชั่น/กำลังภายใน'), ('HORROR', 'สยองขวัญ/ลึกลับ'), ('FANFIC', 'แฟนฟิคชั่น'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='หมวดหมู่')),
                ('rating', models.CharField(choices=[('G', 'ทั่วไป (General)'), ('PG', 'PG-13 (13+)'), ('R18', 'NC-18 (18+)'), ('R20', 'ฉ20 (20+)')], default='G', max_length=5, verbose_name='ระดับเนื้อหา')),
                ('status', models.CharField(choices=[('ONGOING', 'ยังไม่จบ'), ('COMPLETED', 'จบแล้ว')], default='ONGOING', max_length=10, verbose_name='สถานะเรื่อง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='plotcraft.novel'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('weapon', 'Weapon (อาวุธ)'), ('apparel', 'Apparel/Clothing (เครื่องแต่งกาย)'), ('item', 'Item/Consumable (ไอเทม/ยา)'), ('key_item', 'Key Item/Artifact (วัตถุสำคัญ/อาร์ติแฟกต์)'), ('technology', 'Technology (เทคโนโลยี)'), ('vehicle', 'Vehicle (ยานพาหนะ)'), ('other', 'Other (อื่นๆ)')], default='item', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('abilities', models.TextField(blank=True, help_text='ความสามารถพิเศษ หรือผลของไอเทม')),
                ('limitations', models.TextField(blank=True, help_text='เงื่อนไข ข้อจำกัด หรือผลข้างเคียง')),
                ('appearance', models.TextField(blank=True, help_text='ลักษณะภายนอก วัสดุ สี')),
                ('history', models.TextField(blank=True, help_text='ประวัติความเป็นมา ตำนาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='ผู้ครอบครองปัจจุบัน', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='plotcraft.character')),
                ('location', models.ForeignKey(blank=True, help_text='สถานที่ที่เก็บซ่อนอยู่ (ถ้าไม่มีเจ้าของ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='plotcraft.location')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='plotcraft.novel')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='plotcraft.novel'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อตอน')),
                ('content', models.TextField(blank=True, verbose_name='เนื้อหา')),
                ('order', models.IntegerField(default=1, verbose_name='ลำดับตอน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='plotcraft.novel')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อฉาก')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับฉาก')),
                ('status', models.CharField(choices=[('idea', 'Idea (ไอเดียร่าง)'), ('draft', 'Drafting (กำลังเขียน)'), ('revision', 'Revision (รีไรท์)'), ('finished', 'Finished (เสร็จสมบูรณ์)')], default='idea', max_length=20)),
                ('goal', models.TextField(blank=True, help_text='ตัวละครต้องการอะไรในฉากนี้?')),
                ('conflict', models.TextField(blank=True, help_text='อุปสรรคคืออะไร?')),
                ('outcome', models.TextField(blank=True, help_text='ผลลัพธ์เป็นอย่างไร? (ได้/ไม่ได้)')),
                ('content', models.TextField(blank=True, help_text='เนื้อหาฉาก หรือบทร่าง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='appeared_in_scenes', to='plotcraft.character')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='used_in_scenes', to='plotcraft.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='plotcraft.location')),
                ('pov_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pov_scenes', to='plotcraft.character')),
                ('project', models.ForeignKey(help_text='ฉากนี้อยู่ในนิยายเรื่องไหน', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='plotcraft.novel')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Timeline', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelines', to='plotcraft.novel')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_label', models.CharField(default='', max_length=100, verbose_name='ช่วงเวลา/ปี')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับ')),
                ('title', models.CharField(default='', max_length=200, verbose_name='ชื่อเหตุการณ์')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียดเหตุการณ์')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline_events/', verbose_name='รูปภาพเหตุการณ์')),
                ('characters', models.ManyToManyField(blank=True, related_name='timeline_events', to='plotcraft.character')),
                ('related_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotcraft.scene', verbose_name='ตรงกับฉาก')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='plotcraft.timeline')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
