# Generated by Django 5.2.10 on 2026-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotcraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='ฉบับร่าง (ไม่ส่งออก)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='เสร็จสมบูรณ์ (พร้อมส่งออก)'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea (ไอเดียร่าง)'), ('draft', 'Drafting (กำลังเขียน)'), ('finished', 'Finished (เสร็จสมบูรณ์)')], default='idea', max_length=20),
        ),
    ]
