# Generated by Django 5.2.10 on 2026-01-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotcraft', '0002_chapter_is_draft_chapter_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='is_published',
            new_name='is_finished',
        ),
    ]
