# Generated by Django 5.2.10 on 2026-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotcraft', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='plotcraft.character', verbose_name='ความสัมพันธ์กับตัวละครอื่น'),
        ),
    ]
