# Generated by Django 5.2.10 on 2026-01-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotcraft', '0005_alter_character_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FAMILY', 'ครอบครัว/ญาติ'), ('LOVER', 'คนรัก/คู่ครอง'), ('FRIEND', 'เพื่อน/พันธมิตร'), ('ENEMY', 'ศัตรู/คู่แข่ง'), ('MASTER_SERVANT', 'เจ้านาย/ลูกน้อง'), ('OTHER', 'อื่นๆ')], default='FRIEND', max_length=50)),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระบุเพิ่ม (เช่น พี่สาว, เพื่อนสนิท)')),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='plotcraft.character')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='plotcraft.character')),
            ],
        ),
    ]
