# Generated by Django 5.2.11 on 2026-02-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotcraft', '0006_characterrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
